# Generated by Django 4.2.3 on 2023-07-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cpf', models.TextField(max_length=15)),
                ('data_nasc', models.DateField(null=True)),
                ('emial', models.TextField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('genero', models.TextField()),
            ],
        ),
    ]
