# Generated by Django 4.2.3 on 2023-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_de_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
