# Generated by Django 4.2.3 on 2023-07-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_de_usuario', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outros', 'Outros'), ('Prefiro não dizer', 'Prefiro não dizer')], max_length=25),
        ),
    ]
