# Generated by Django 4.2.3 on 2023-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro_de_usuario', '0003_alter_usuario_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='emial',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros'), ('PND', 'Prefiro não dizer')], max_length=3),
        ),
    ]
